### ISSUE TITLE
SASS imports don't work in Liquid files

### ISSUE THREAD

**Issue by brgrz** [VirtoCommerce/vc-storefront-core#167] opened 2018-10-13 13:42 UTC
Trying to import some Foundation mixins from .scss files into .scss.liquid files and it doesn't work at all.

```
An unhandled exception occurred while processing the request.
SaasCompileException: Failed to compile sass file "/Themes/site/vc-custom-theme/assets/default.foundation.scss.liquid"

Line: 

Compiler error: LibSassHost.SassСompilationException: Error: File to import not found or unreadable: ./foundation-sites/scss/util/_breakpoint.scss.
on line 1 of stdin
>> @import "./foundation-sites/scss/util/_breakpoint.scss";
^

at LibSassHost.SassCompiler.EndCompile(SassContextBase context)
at LibSassHost.SassCompiler.Compile(String content, CompilationOptions options)
at VirtoCommerce.LiquidThemeEngine.ShopifyLiquidThemeEngine.GetAssetStream(String filePath) in H:\GitHub\brgrz\vc-storefront-core\VirtoCommerce.LiquidThemeEngine\ShopifyLiquidThemeEngine.cs:line 190
VirtoCommerce.LiquidThemeEngine.ShopifyLiquidThemeEngine.GetAssetStream(string filePath) in ShopifyLiquidThemeEngine.cs, line 197
```

**Comment by Woland2k** [comment] 2018-10-13 23:14
Hi, we use standard lib sass library to render SASS files, you can check their page for some guidance either https://github.com/Taritsyn/LibSassHost or http://sass-lang.com/libsass.

**Comment by asvishnyakov** [comment] 2018-10-19 03:13
Duplicate of #89

**Closed by asvishnyakov** 2018-10-19 03:13 UTC
